logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[file]

[entryPoints]
  [entryPoints.http]
  address = ":{{ .Env.PORT_HTTP }}"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":{{ .Env.PORT_HTTPS }}"
  [entryPoints.https.auth.basic]
  users = [ "{{ .Env.HTTP_BASIC_USER }}:{{ .Env.HTTP_BASIC_PASSWORD }}" ]
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "certs/monitoring.crt"
      keyFile = "certs/monitoring.key"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false

# [acme]
# email = "systems+letsencrypt@newknowledge.io"
# storage = "acme.json"
# entryPoint = "https"
# onHostRule = true
