version: '2'


services:

  master-nodeexporter:
    extends:
      file: docker-compose.yml
      service: master-nodeexporter

  master-cadvisor:
    extends:
      file: docker-compose.yml
      service: master-cadvisor

  prometheus:
    extends:
      file: docker-compose.yml
      service: prometheus
    environment:
      - VIRTUAL_HOST=prometheus.${DOMAIN}
    networks:
      - default
      - node_ingress
    labels:
      - "traefik.backend=prometheus"
      - "traefik.docker.network=${INGRESS_NETWORK}"
      - "traefik.frontend.rule=Host:prometheus.${DOMAIN}"
      - "traefik.frontend.auth.basic=admin:${PASSWORD}"
      - "traefik.enable=true"

  blackboxprober:
    extends:
      file: docker-compose.yml
      service: blackboxprober

  grafana:
    extends:
      file: docker-compose.yml
      service: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD}
      - VIRTUAL_HOST=grafana.${DOMAIN}
    networks:
      - default
      - node_ingress
    labels:
      - "traefik.backend=grafana"
      - "traefik.docker.network=${INGRESS_NETWORK}"
      - "traefik.frontend.rule=Host:grafana.${DOMAIN}"
      - "traefik.frontend.auth.basi c=admin:${PASSWORD}"
      - "traefik.enable=true"

  alertmanager:
    extends:
      file: docker-compose.yml
      service: alertmanager
    environment:
      - VIRTUAL_HOST=alertmanager.${DOMAIN}
    networks:
      - default
      - node_ingress
    labels:
      - "traefik.backend=alertmanager"
      - "traefik.docker.network=${INGRESS_NETWORK}"
      - "traefik.frontend.rule=Host:alertmanager.${DOMAIN}"
      - "traefik.frontend.auth.basic=admin:${PASSWORD}"
      - "traefik.enable=true"

networks:
  default:
    external:
      name: monitoring_logging
  node_ingress:
    external:
      name: ${INGRESS_NETWORK}
